name: TDS
channels:
  - defaults
dependencies:
  - python=3.7
  - requests
  - numpy
  - pandas
  - geopandas
  - descartes
  - scipy
  - matplotlib
  - seaborn
  - openpyxl
  - jupyter
  - autopep8
  - conda-forge::jupyter_contrib_nbextensions
  - pymc3
  - scikit-learn
  - pip:
    - imblearn==0.0
    - colorama==0.4.4
